name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.15.1'
      - name: Install dependencies
        run: |
          yarn policies set-version '1.22.10'
          yarn install
      - name: Run tests
        run: yarn test